export TestControl from './test/TestControl'
export ManagerControl from './manager/ManagerControl'
export UserControl from './user/UserControl'
export PageControl from './page/PageControl'
export ApiManagerControl from './api/ApiManagerControl'
export DbInfoControl from './api/DbInfoControl'
export SystemControl from './api/SystemControl'
export LogRegControl from './logReg/LogRegControl'
